CREATE TABLE IF NOT EXISTS user (
  UserId       INT(10)      NOT NULL AUTO_INCREMENT,
  FirstName    VARCHAR(255) NOT NULL,
  LastName     VARCHAR(255) NOT NULL,
  Email        VARCHAR(255) NOT NULL,
  Phone        VARCHAR(10)  NOT NULL,
  DateSignedUp DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (UserId)
);

CREATE TABLE IF NOT EXISTS login (
  LoginId  INT(10)      NOT NULL AUTO_INCREMENT,
  UserName VARCHAR(255) NOT NULL,
  Password VARCHAR(255) NOT NULL,
  UserId   INT(10)      NOT NULL,
  PRIMARY KEY (LoginId),
  CONSTRAINT login_userId_fk
  FOREIGN KEY (UserId)
  REFERENCES user (UserId)
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS admin (
  AdminId INT(10) NOT NULL AUTO_INCREMENT,
  UserId  INT(10) NOT NULL,
  PRIMARY KEY (AdminId),
  CONSTRAINT admin_userId_fk
  FOREIGN KEY (UserId)
  REFERENCES user (UserId)
    ON DELETE CASCADE
);
